[package]
name = "hotbolt-runner"
version = "0.1.0"
authors = ["Daniel Hrabovcak <thespiritxiii@gmail.com>"]
edition = "2018"

[dependencies]
hotbolt_ffi = { path = "../hotbolt_ffi" }
env_logger = "0.7.1"
libloading = "0.6.2"
log = "0.4.11"
notify = "5.0.0-pre.3"
toml = "0.5.6"

[dependencies.serde]
version = "1.0.114"
features = ["derive"]
