[package]
name = "counter"
version = "0.1.0"
authors = ["Daniel Hrabovcak <thespiritxiii@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "hotbolt_runnable"
crate-type = ["cdylib"]

[dependencies]
hotbolt = { path = "../../hotbolt" }

[features]
hotbolt_erase = []
