[package]
name = "hotbolt-test"
version = "0.1.0"
authors = ["Daniel Hrabovcak <thespiritxiii@gmail.com>"]
edition = "2021"
rust-version = "1.56"
publish = false

[dependencies]
log = "0.4.0"
env_logger = "0.9.0"
# TODO: Do we need full?
tokio = { version = "1.13.0", features = ["full"] }
